language: go

go:
- 1.6
- tip

matrix:
  allow_failures:
  - go: tip

before_install:
- go get -v github.com/mattn/goveralls
- go get -v github.com/onsi/ginkgo
- go get -v github.com/onsi/gomega
- go get -v github.com/golang/lint/golint
- go install -v github.com/onsi/ginkgo/ginkgo
- curl https://glide.sh/get | sh

install:
- glide install

script: PATH=$HOME/gopath/bin:$PATH bin/test

after_success:
- 'echo "mode: set" > all.coverprofile'
- 'find . -name "*.coverprofile" -exec grep -v mode: {} >> all.coverprofile \;'
- "$HOME/gopath/bin/goveralls -coverprofile=all.coverprofile -repotoken=$COVERALLS_TOKEN"
