trigger:
  batch: false
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
  GO_VERSION: '1.13'
jobs:
- job: UnitTests
  pool:
    vmImage: "Ubuntu-16.04"
  steps:
  - task: GoTool@0
    displayName: Use Golang $(GO_VERSION)
    inputs:
      version: $(GO_VERSION)
      gobin: $(Agent.BuildDirectory)/gopath/bin
      steps:
  - task: Go@0
    displayName: Get Go dependencies
    inputs:
      command: 'get'
      arguments: "github.com/onsi/ginkgo
                  github.com/onsi/gomega
                  github.com/Masterminds/glide
                  golang.org/x/lint/golint"
      workingDirectory:
  - task: Go@0
    displayName: Install Go dependencies
    inputs:
      command: 'install'
      arguments: "github.com/onsi/ginkgo/ginkgo
                  github.com/Masterminds/glide"
      workingDirectory:
  - script: |
      mkdir -p '$(GOBIN)'
      mkdir -p '$(GOPATH)/pkg'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      mv !(gopath) '$(modulePath)'
      echo '##vso[task.prependpath]$(GOBIN)'
    displayName: 'Set up the Go workspace'
  - script: $(GOBIN)/glide install
    workingDirectory: $(modulePath)
    displayName: Install dependencies
  - script: bin/test
    workingDirectory: $(modulePath)
    displayName: Run unit tests
