name: Run Tests

on:
  pull_request:
    branches:
      - master

concurrency:
  group: unit-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@v2.1.4
      - name: Test
        run: bin/test -v
